PTT_PATH := ../tracelib
PROGRAMS := dotprod matmul prodcons blackscholes

dotprod_SOURCES := dotprod.c
dotprod_PCF     := dotprod.pcf

matmul_SOURCES := matmul.c
matmul_PCF     := matmul.pcf

prodcons_SOURCES := prodcons.c
prodcons_PCF     := prodcons.pcf

blackscholes_SOURCES := blackscholes.c
blackscholes_PCF     := bs.pcf
blackscholes_LIBS    := m

include $(PTT_PATH)/rules.mk

