PTT_PATH := ../tracelib
PROGRAMS := dotprod matmul prodcons blackscholes

dotprod_SOURCES      := dotprod.c
matmul_SOURCES       := matmul.c
prodcons_SOURCES     := prodcons.c
blackscholes_SOURCES := blackscholes.c

blackscholes_LIBS := m

include $(PTT_PATH)/rules.mk

